[Scia Reto](https://sciareto.org) mind map   
> __version__=`1.1`,showJumps=`true`
---

# ORDER

## 주문

### 주문하기

#### 주문등록

##### 동시에 여러명이 등록해도 상품 재고에 따라 주문 성공 / 실패여부가 명확하게 반영되는지

##### 상태

###### ACCEPT\(인수\)으로 주문 등록 되어있는지

##### 필드값 일치

###### 주문등록시 단건에 대한 필드값이 서로 일치하는지 체크

##### Race Condition 체크

###### 주문이 동시에 10 , 100 , 1000건이 등록되어도 정상적으로 해당 주문이 10, 100, 1000 건의 카운트에 맞게 들어가있는지

##### 요청 파라미터 검증

###### 요청 파라미터에 NULL 값이 들어오는 경우 NPE 발생

#### 상품 재고 하락

##### 상품 쪽에서 테스트해야함

#### 회원 잔액 하락

##### 회원 쪽에서 테스트해야함

### 주문 수정

#### 주문 수정

##### 회원 쪽에서 테스트해야함

##### 특정 수정된 내역에 올바르게 반영되어있는지

##### 요청 파라미터검증

###### 요청 파라미터에 NULL 값이 들어오는 경우 NPE 발생

#### 상품 재고의 수정

##### 상품쪽에서 테스트해야할 사항

### 주문삭제

#### 주문 삭제

##### SOFT DELETE 를 전제합니다

###### Persistence

####### 주문 삭제

######## 주문 삭제에 대한 성공시 exception 이 발생하지 않아야함

######## 주문 삭제에 대한 실패시 databaseoperationexception과 에러 문구 체크해야함<br/>
> align=`center`


####### 주문\-상품 삭제

######## 주문 \- 상품 삭제에 대한 성공시 exception 이 발생하지 않아야함

######## 주문 \- 상품 삭제에 대한 실패시 databaseoperationexception과 에러 문구 체크해야함<br/>
> align=`center`


###### mapper

####### 주문\-상품 삭제

######## 삭제된 데이터 삭제 이전  / 이후의 속성의 동일여부 체크

######## 삭제일 업데이트 여부 체크

######## 삭제된 데이터 값의 사이즈가 이전과 동일한지 체크

####### 주문 삭제

######## 삭제일 업데이트 여부 체크

######## 주문\-상품 

###### service

####### 주문삭제

######## 주문 삭제 수행시 자식 주문\-상품 값도 soft delete 되어야 합니다\.

######### 주문 삭제

########## 메서드 수행시 예외발생에 따른 테스트

######### 주문\-상품 삭제

########## 메서드 수행시 예외 발생에 따른 테스트

##### 요청 파라미터 검증

###### 요청 파라미터에 NULL 값이 들어오는 경우 NPE 발생

#### 상품 재고 증가

##### 상품쪽에서 테스트해야함

#### 회원 잔액 증가

##### 회원쪽에서 테스트해야함