spring:
  jpa:
    open-in-view: 'false'
  main:
    banner-mode: 'off'
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: local
  servlet:
    multipart:
      # maximum file size
      max-file-size: 10MB
      # maximum request size
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:sqlmap/com/psj/itembrowser/*.xml

customed:
  table:
    schema: item-browser

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    url: /static/openapi3.yaml
    path: /docs/swagger

app:
  domain:
    server: https://item.co.kr
    local: http://localhost:8080
    dev: http://item.dev.com

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  access-token:
    expiration-time: '3600' # 1 hour
  refresh-token:
    expiration-time: '31536000' # 1 year


pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

file:
  upload-dir: ./src/main/resources/static/uploads/

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
        retryer: full

juso:
  url: https://business.juso.go.kr/addrlink/addrLinkApiJsonp.do
  confmKey: classpath:juso.key

server:
  error:
    include-stacktrace: never