spring:
  sql:
    init:
      schema-locations: classpath:/truncate-procedure.sql, classpath:/schema.sql
      mode: always
      encoding: UTF-8
  datasource:
    password: 2H#@(#Jksj@kkwje
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: item-admin
    url: jdbc:log4jdbc:mysql://localhost:3306/item-browser?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=UTF-8
app:
  domain: http://localhost:8080
logging:
  level:
    jdbc:
      audit: 'off'
      connection: 'off'
      sqlonly: info
      resultset: 'off'
      resultsettable: 'off'
      sqltiming: 'off'