INSERT INTO member (EMAIL, PASSWORD, FIRST_NAME, LAST_NAME, GENDER, PHONE_NUMBER, BIRTHDAY, ROLE,
                    STATUS, ADDRESS_MAIN,
                    ADDRESS_SUB, ZIP_CODE, CREATED_DATE, UPDATED_DATE, DELETED_DATE,
                    LAST_LOGIN_DATE)
VALUES ('test@test.com', '{bcrypt}jiohioqh123!@#', 'Park', 'SangJun', 'MEN', '010-2520-4929', NOW(),
        'ROLE_CUSTOMER',
        'ACTIVE', 'ADDRESS_MAIN 1', 'ADDRESS_SUB 1', '01234', NOW(), NOW(), NOW(), NOW());


INSERT INTO member_refresh_token (EMAIL, REFRESH_TOKEN, CREATED_DATE)
VALUES ('test@test.com',
        'eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoidGVzdEB0ZXN0LmNvbSIsImV4cCI6MTcwNjUxMjQ4OCwiaWF0IjoxNzA2NTA4ODg4LCJzY29wZSI6IlJPTEVfQ1VTVE9NRVIgUk9MRV9TVE9SRV9NQU5BR0VSIn0.EQzKG8ptnwFvhLDktEe4Nqe7yycoVixbQpLW6mHz3hWPGJBum2I9G_zsSFeluk4a2lJ0e0gYiJQ7-dMyMe8PXrVoOeiLtCpsYwChICILJbCrqUxil7ufD-3yLnHkauYQi2xTPmBm-Nay2-3MRtah-fTDY5dQ-IwpSY0rH8Gh935a6zxHyJTvp_c-JYVI8bjWDZviNIG_k2u7rKCxPNrFEZHgkjOCgjH6t15xFfrhA8sP4Pn0QgsJcK4Y74f7Am55Hz18QWIZ05JrmJUuDL8Gmto5X3sXmANaUoV1IacTbhgvJCUBi89LjnQkPEvU4sJqB0d6N-ITbaTCowxeGhoOKQ',
        NOW())
;